### ISSUE TITLE
在线部署只支持.wasm吗？

### ISSUE THREAD

**Issue by leiweihao** [xuperchain/xuper-java-sdk#27]

**Comment by urontlee** [comment]
在github 上的代码是支持部署 native 、 wasm 、evm合约的，可以看下：https://github.com/xuperchain/xuper-java-sdk/blob/master/src/main/java/com/baidu/xuper/api/XuperClient.java

但是 maven 仓库中还不支持 native

**Comment by leiweihao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by leiweihao** [comment]
> 好的 谢谢    我在使用xbench压测工具  在make之后  在output/bin目录  并没有生成对应的文件

**Comment by leiweihao** [comment]
![Q_R)Y(`MKH8SBXK_LSWJF49](https://user-images.githubusercontent.com/57650467/146728872-a01a0b1b-a106-43b0-9dd5-c023d7bb0dd0.png)

**Comment by leiweihao** [comment]
> 在github 上的代码是支持部署 native 、 wasm 、evm合约的，可以看下：https://github.com/xuperchain/xuper-java-sdk/blob/master/src/main/java/com/baidu/xuper/api/XuperClient.java
> 
> 但是 maven 仓库中还不支持 native



> 在github 上的代码是支持部署 native 、 wasm 、evm合约的，可以看下：https://github.com/xuperchain/xuper-java-sdk/blob/master/src/main/java/com/baidu/xuper/api/XuperClient.java
> 
> 但是 maven 仓库中还不支持 native
