### ISSUE TITLE
RWACL_INVALID_ERROR

### ISSUE THREAD

**Issue by dockerwanfeng** [xuperchain/xuper-java-sdk#33]
Error RWACL_INVALID_ERROR while PostTx???

**Comment by dockerwanfeng** [comment]
账户余额：mJiPYDgxxxxxxxxxxxxxxxxx  299600
Transaction transfer = client.transfer(accountFromFile, "mJiPYDgxxxxxxxxxxxxxxxxx", BigInteger.valueOf(99600), "1");

**Comment by uaanaa** [comment]
连接的是本地的链吗？还是开放网络

**Comment by dockerwanfeng** [comment]
开放网络：

XuperClient client = new XuperClient("39.156.69.83:37100");


urnotlee ***@***.***> 于2022年2月14日周一 15:39写道：

**Comment by dockerwanfeng** [comment]
[image: image.png][image: image.png]我感到很奇怪。。。

feng wei ***@***.***> 于2022年2月14日周一 15:47写道：

**Comment by uaanaa** [comment]
1. java sdk 使用 2.0的
2. 在初始化client 之前  Config.setConfigPath("conf/sdk.yaml"); 连接开放网络需要开启背书服务sdk.yaml 从这里copy到本地：https://github.com/xuperchain/xuper-java-sdk/blob/master/src/main/java/com/baidu/xuper/conf/sdk.yaml
3. RWACL 一般是账户不正确，需要再检查一下

**Comment by dockerwanfeng** [comment]
嗯，我再看看

**Comment by uaanaa** [comment]
另外，忘记说，开放网络是不支持转账操作的。可以部署合约使用

**Comment by dockerwanfeng** [comment]
开放网络是不支持转账操作的？也就是账户资源，是不能转账给其他账户的是吗？我觉得可能是这个原因

**Comment by uaanaa** [comment]
对，开放网络的账户资源不能转给别的账户

**Comment by dockerwanfeng** [comment]
[image: image.png]
[image: image.png]

我在账号下，安装完成了一个合约：
然后我去调用合约：Transaction tx = client.queryEVMContract(account, "Counter",
"getOwner", args);
出现：UNKNOWN: identity check failed

urnotlee ***@***.***> 于2022年2月14日周一 17:12写道：

**Comment by dockerwanfeng** [comment]
你好。调用静态合约有问题，提示： UNKNOWN: identity check failed
身份认证失败，怎么处理？

feng wei ***@***.***> 于2022年2月15日周二 11:54写道：
