### ISSUE TITLE
UNKNOWN: identity check failed

### ISSUE THREAD

**Issue by dockerwanfeng** [xuperchain/xuper-java-sdk#34]
我在账号下，安装完成了一个合约：

![image](https://user-images.githubusercontent.com/44518865/153989632-aec7d261-138f-48d2-979e-fc0db7a7050b.png)
![image](https://user-images.githubusercontent.com/44518865/153989670-ecdcb4ba-c0dc-441c-a043-1efb2f745ea2.png)

然后我去调用合约：Transaction tx = client.queryEVMContract(account, "Counter", "getOwner", args);
出现：UNKNOWN: identity check failed

**Comment by dockerwanfeng** [comment]
![image](https://user-images.githubusercontent.com/44518865/153989813-fc501961-159a-459c-adf0-50955a66f5b7.png)

**Comment by godeamon** [comment]
调用时使用的 account 是从网站上下载的私钥吗？

**Comment by dockerwanfeng** [comment]
已经解决

**Comment by duchangyu** [comment]
@dockerwanfeng   我也遇到这个问题，你怎么解决的？

**Comment by uaanaa** [comment]
> @dockerwanfeng 我也遇到这个问题，你怎么解决的？

私钥要用开放网络工作台下载的完成实名认证的。
