### ISSUE TITLE
调用合约方法提示 “ACL not enough”

### ISSUE THREAD

**Issue by MoxiseTou** [xuperchain/xuper-java-sdk#68]
```java
    public static void addScore(String userid,String data){
        //合约名称
        String contractName = "xxx";
        //合约方法
        String contractMethod = "xxx";
        //合约账号
        String contractAccount = "XC0553xxxxxx@xuper";

        XuperClient client = new XuperClient("39.156.69.83:37100");
        Account account = Account.getAccountFromFile(S_KEY_PATH,PW);
        Config.setConfigPath(SDK_FILE_PATH);

        //在调用合约时，如果 SetContractAccount，那么此次调用的发起者为合约账户。即：msg.sender 为合约账户转换后的EVM地址。
        account.setContractAccount(contractAccount);

        // 开放网络不允许转账，所以在调用合约时 amount 参数要给0
        Map<String,String> params = new HashMap<>();
        params.put("userid", userid);
        params.put("data", data);

        // 开放网络不允许转账，所以在调用合约时 amount 参数要给0
        Transaction tx = client.invokeEVMContract(account,contractName, contractMethod, params, BigInteger.ZERO);
        System.out.println(tx.getContractResponse().getBodyStr());
    }
```
这是我的代码，调用的时候提示“ UNKNOWN: Err:500-50400-verify tx failed+err:ACL not enough ”。翻阅了issues，看到有说sdk.yaml问题配置文件问题，我检查了，是从接入指南里复制过来的，内容如下：
```properties
# endorseService Info
endorseServiceHost: "39.156.69.83:37100"
complianceCheck:
  # 是否需要进行合规性背书
  isNeedComplianceCheck: true
  # 是否需要支付合规性背书费用
  isNeedComplianceCheckFee: true
  # 合规性背书费用
  complianceCheckEndorseServiceFee: 400
  # 支付合规性背书费用的收款地址
  complianceCheckEndorseServiceFeeAddr: aB2hpHnTBDxko3UoP2BpBZRujwhdcAFoT
  # 如果通过合规性检查，签发认证签名的地址
  complianceCheckEndorseServiceAddr: jknGxa6eyum1JrATWvSJKW3thJ9GKHA9n
#创建平行链所需要的最低费用
minNewChainAmount: "100"
crypto: "xchain"
txVersion: 3
```
但实际运行还是提示这个
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/93264c42-fe5a-494c-9025-03c4b04b1c00)

**Comment by godeamon** [comment]
@MoxiseTou 你好，`String contractAccount = "XC0553xxxxxx@xuper"; ` 这合约账户是从开放网络网站上复制下来的吗？另外使用的公私钥需要也是从开放网络下载的，这样才能对应上。

**Comment by MoxiseTou** [comment]
@godeamon 你好，是我从自己创建的合约上复制的，私钥是从我自己账号下载的。我附下图。您看下我获取的地方是否正确
合约账号：
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/c43beb5a-4e78-4e43-8fb2-45c9caae8b15)
私钥：
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/87153cde-41fc-498d-828d-34d26dc1e2a4)
公钥倒是没有，`Account.getAccountFromFile(S_KEY_PATH,PW);`的S_KEY_PATH目录里只放了一个private.key文件。
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/115aa140-e925-4941-baa4-bc3ab1432534)

**Comment by godeamon** [comment]
@MoxiseTou 调用合约时可以不使用合约账户，直接用私钥就可以。

**Comment by MoxiseTou** [comment]
@godeamon 我尝试把`account.setContractAccount(contractAccount);`这行代码去掉运行，依然提示ACL not enough。前面说的公钥私钥和合约名称，是不是我取的不对

**Comment by godeamon** [comment]
> @godeamon 我尝试把`account.setContractAccount(contractAccount);`这行代码去掉运行，依然提示ACL not enough。前面说的公钥私钥和合约名称，是不是我取的不对

Config.setConfigPath(SDK_FILE_PATH);
将这行代码移动到最前面试一下

**Comment by MoxiseTou** [comment]
@godeamon 非常感谢，确实是因为这行代码在后面的原因，放到前面可以正常请求到了。另想问下有的方法返回有加密，不知道我们有解密方法吗，翻阅了文档和项目并没有看见。
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/b2fe0094-b2c5-494f-9e62-b90dd757c500)

重新翻阅了下网站，在使用文档里没有问题，接入指南里顺序确实是反的。地址是https://xuper.baidu.com/n/xuperdoc/v5.3/xuperos/xuperos_java.html
![image](https://github.com/xuperchain/xuper-java-sdk/assets/26769260/33a7d5fb-8f20-4b7e-a866-773defbb0b1e)
